image: dlp

stages:
- cours
- tme


ILP1:
  stage: cours
  script: >
    /home/dlp/run.sh -id ILP1 -name ILP1
    com.paracamplus.ilp1.tools.test.FileToolTest
    com.paracamplus.ilp1.tools.test.ProgramCallerTest
    com.paracamplus.ilp1.interpreter.test.InterpreterTest
    com.paracamplus.ilp1.compiler.test.CompilerTest


TME1:
  stage: tme
  script: >
   /home/dlp/run.sh -id TME1 -name TME1
   com.paracamplus.ilp1.ilp1tme1.test.TestCompiler 
   com.paracamplus.ilp1.ilp1tme1.test.TestInterprete
   com.paracamplus.ilp1tme1.sequence.ASTsequenceTest

   
TME2:
  stage: tme
  script: >
   /home/dsl/run.sh -id TME2 -name TME2
   com.paracamplus.ilp1.ilp1tme2.ex1.InterpreteTest
  artifacts:
   reports:
     junit: report.xml

